version: '3.9'
services:
  web:
    command: python3 app/app.py  
    image: thang59/a3-assignment
    environment:
      - HOST=0.0.0.0
      - PORT=80

    labels:
      - traefik.enable=true
      - traefik.http.services.web-st124642.loadbalancer.server.port=80
      - traefik.http.routers.web-st124642.tls=true
      - traefik.http.routers.web-st124642.rule=Host(`st124642.ml.brain.cs.ait.ac.th`)
      - traefik.http.routers.web-st124642.tls.certresolver=production
      - traefik.http.routers.web-st124642.entrypoints=websecure
    networks:
      - default
      - traefik_default

networks:
  default:
  traefik_default:
    external: true